### ISSUE TITLE
Support for AWS_SDK_LOAD_CONFIG

### ISSUE THREAD

**Issue by ryansonshine** [awslabs/aws-web3-http-provider#5]
Currently `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` must be set to use this package.

Is there a limitation preventing us from supporting `AWS_SDK_LOAD_CONFIG` to be able to omit the access keys from the env variables?

Will be looking into this later but if there's already been some investigation done on this please let me know.

**Comment by cayblood** [comment]
I'm not familiar with how `AWS_SDK_LOAD_CONFIG` works, but I assume that you could adapt the existing code to use whatever API calls might be necessary to extract the needed parameters. I'm no longer working for AWS, so I'm unable to accept pull requests, but my former colleague @forrest-not-gump should be able to.

**Comment by ryansonshine** [comment]
Thanks! We're working on a PR and will reach out when it's ready.
